// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package calendar

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// event
type Event struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Duration             int64                `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Header               string               `protobuf:"bytes,4,opt,name=header,proto3" json:"header,omitempty"`
	Description          string               `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	User                 string               `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Event) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Event) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Event) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *Event) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Event) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

// event list
type EventList struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventList) Reset()         { *m = EventList{} }
func (m *EventList) String() string { return proto.CompactTextString(m) }
func (*EventList) ProtoMessage()    {}
func (*EventList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1}
}

func (m *EventList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventList.Unmarshal(m, b)
}
func (m *EventList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventList.Marshal(b, m, deterministic)
}
func (m *EventList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventList.Merge(m, src)
}
func (m *EventList) XXX_Size() int {
	return xxx_messageInfo_EventList.Size(m)
}
func (m *EventList) XXX_DiscardUnknown() {
	xxx_messageInfo_EventList.DiscardUnknown(m)
}

var xxx_messageInfo_EventList proto.InternalMessageInfo

func (m *EventList) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "calendar.Event")
	proto.RegisterType((*EventList)(nil), "calendar.EventList")
}

func init() {
	proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e)
}

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x50, 0x31, 0x4f, 0xf3, 0x30,
	0x14, 0x94, 0xbf, 0xb6, 0x51, 0xe3, 0x0c, 0x9f, 0xe4, 0x01, 0x59, 0x59, 0x88, 0xba, 0x90, 0xa5,
	0xb6, 0x54, 0x58, 0x58, 0x41, 0xdd, 0x98, 0x22, 0x26, 0x16, 0xe4, 0xc4, 0x8f, 0xd4, 0x52, 0x62,
	0x47, 0xb6, 0x43, 0xc5, 0xbf, 0xe3, 0xa7, 0xa1, 0xbc, 0x24, 0x88, 0xc9, 0xbe, 0x7b, 0x77, 0xe7,
	0xe7, 0xa3, 0x19, 0x7c, 0x82, 0x8d, 0x62, 0xf0, 0x2e, 0x3a, 0xb6, 0x6f, 0x54, 0x07, 0x56, 0x2b,
	0x9f, 0xdf, 0xb6, 0xce, 0xb5, 0x1d, 0x48, 0xe4, 0xeb, 0xf1, 0x43, 0x46, 0xd3, 0x43, 0x88, 0xaa,
	0x1f, 0x66, 0xe9, 0xe1, 0x9b, 0xd0, 0xdd, 0x79, 0xb2, 0x32, 0x46, 0xb7, 0xe3, 0x68, 0x34, 0x27,
	0x05, 0x29, 0xd3, 0x0a, 0xef, 0xec, 0x91, 0xd2, 0x10, 0x95, 0x8f, 0xef, 0x93, 0x8d, 0xff, 0x2b,
	0x48, 0x99, 0x9d, 0x72, 0x31, 0x67, 0x8a, 0x35, 0x53, 0xbc, 0xae, 0x99, 0x55, 0x8a, 0xea, 0x09,
	0xb3, 0x9c, 0xee, 0xf5, 0xe8, 0x55, 0x34, 0xce, 0xf2, 0x4d, 0x41, 0xca, 0x4d, 0xf5, 0x8b, 0xd9,
	0x0d, 0x4d, 0x2e, 0xa0, 0x34, 0x78, 0xbe, 0xc5, 0xc7, 0x16, 0xc4, 0x0a, 0x9a, 0x69, 0x08, 0x8d,
	0x37, 0x03, 0xda, 0x76, 0x38, 0xfc, 0x4b, 0xe1, 0x92, 0x01, 0x3c, 0x4f, 0x96, 0x25, 0x03, 0xf8,
	0xc3, 0x03, 0x4d, 0xf1, 0x07, 0x2f, 0x26, 0x44, 0x76, 0x47, 0x13, 0x6c, 0x22, 0x70, 0x52, 0x6c,
	0xca, 0xec, 0xf4, 0x5f, 0xac, 0x5d, 0x08, 0x14, 0x55, 0xcb, 0xf8, 0xe9, 0xfc, 0xf6, 0xdc, 0x9a,
	0x78, 0x19, 0x6b, 0xd1, 0xb8, 0x5e, 0x2a, 0xab, 0xbf, 0xae, 0xee, 0x2a, 0x5b, 0xd7, 0x29, 0xdb,
	0x1e, 0x3b, 0x08, 0xc1, 0xd9, 0x20, 0xe7, 0xf3, 0xb8, 0x46, 0x48, 0x63, 0x23, 0x78, 0xab, 0x3a,
	0xb9, 0x32, 0x75, 0x82, 0x2d, 0xdc, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x05, 0x20, 0x97, 0x5a,
	0x80, 0x01, 0x00, 0x00,
}
