version: '3.7'

services:

  db:
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    image: "postgres:12.2-alpine"
    networks:
      dbnet:
        aliases:
        - db
    ports:
    - "5432:5432"
    volumes:
    - "${POSTGRES_VOL}:/var/lib/postgresql/data"

  mq:
    image: "rabbitmq:3-management"
    networks:
      mqnet:
        aliases: 
        - mq
    ports:
    - "5672:5672"
    - "15672:15672"
    volumes:
    - "${RABBITMQ_VOL}:/var/lib/rabbitmq"

  dbmigrate:
    command:
    - -path=/migrations
    - -database
    - postgres://postgres:${POSTGRES_PASSWORD}@db:5432/postgres?sslmode=disable&connect_timeout=30&x-migrations-table=migrate
    - up
    depends_on:
    - db
    image: "migrate/migrate:latest"
    networks:
    - dbnet
    volumes:
    - "./sql:/migrations"  

  apiserver:
    build:
      context: .
      dockerfile: deploy/apiserver/Dockerfile
    depends_on:
    - db
    - dbmigrate
    ports:
    - "8888:9090"
    networks:
    - dbnet
    volumes:
    - "${CONFIG_PATH}:/app/config.yaml:ro"
  
  scheduler:
    build:
      context: .
      dockerfile: deploy/scheduler/Dockerfile
    depends_on:
    - db
    - dbmigrate
    - mq
    networks:
    - dbnet
    - mqnet
    volumes:
    - "${CONFIG_PATH}:/app/config.yaml:ro"
  
  sender:
    build:
      context: .
      dockerfile: deploy/sender/Dockerfile
    depends_on:
    - mq
    networks:
    - mqnet
    volumes:
    - "${CONFIG_PATH}:/app/config.yaml:ro"

networks:
  dbnet:
  mqnet:
