# config file example
grpc_listen: 127.0.0.1:9090
http_listen: 127.0.0.1:8080
log_console: true
#log_file: calendar.log
log_level: debug
# storage type
storage_type: database

# db settings
db:
  host: 127.0.0.1
  port: 5432
  name: postgres
  user: calendar
  password: calendar

# rabbitmq settings
rabbitmq:
  host: 127.0.0.1
  port: 5672
  queue: nofifications
  user: guest
  password: guest
