// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package eventapi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// event
type Event struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Duration             int64                `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Header               string               `protobuf:"bytes,4,opt,name=header,proto3" json:"header,omitempty"`
	Description          string               `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	User                 string               `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Event) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Event) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Event) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *Event) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Event) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

// event list
type EventList struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventList) Reset()         { *m = EventList{} }
func (m *EventList) String() string { return proto.CompactTextString(m) }
func (*EventList) ProtoMessage()    {}
func (*EventList) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *EventList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventList.Unmarshal(m, b)
}
func (m *EventList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventList.Marshal(b, m, deterministic)
}
func (m *EventList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventList.Merge(m, src)
}
func (m *EventList) XXX_Size() int {
	return xxx_messageInfo_EventList.Size(m)
}
func (m *EventList) XXX_DiscardUnknown() {
	xxx_messageInfo_EventList.DiscardUnknown(m)
}

var xxx_messageInfo_EventList proto.InternalMessageInfo

func (m *EventList) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

// delete event response code
type EventDeleteStatus struct {
	Deleted              bool     `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventDeleteStatus) Reset()         { *m = EventDeleteStatus{} }
func (m *EventDeleteStatus) String() string { return proto.CompactTextString(m) }
func (*EventDeleteStatus) ProtoMessage()    {}
func (*EventDeleteStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *EventDeleteStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventDeleteStatus.Unmarshal(m, b)
}
func (m *EventDeleteStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventDeleteStatus.Marshal(b, m, deterministic)
}
func (m *EventDeleteStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDeleteStatus.Merge(m, src)
}
func (m *EventDeleteStatus) XXX_Size() int {
	return xxx_messageInfo_EventDeleteStatus.Size(m)
}
func (m *EventDeleteStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDeleteStatus.DiscardUnknown(m)
}

var xxx_messageInfo_EventDeleteStatus proto.InternalMessageInfo

func (m *EventDeleteStatus) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

// event date
type EventDate struct {
	Date                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EventDate) Reset()         { *m = EventDate{} }
func (m *EventDate) String() string { return proto.CompactTextString(m) }
func (*EventDate) ProtoMessage()    {}
func (*EventDate) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *EventDate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventDate.Unmarshal(m, b)
}
func (m *EventDate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventDate.Marshal(b, m, deterministic)
}
func (m *EventDate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDate.Merge(m, src)
}
func (m *EventDate) XXX_Size() int {
	return xxx_messageInfo_EventDate.Size(m)
}
func (m *EventDate) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDate.DiscardUnknown(m)
}

var xxx_messageInfo_EventDate proto.InternalMessageInfo

func (m *EventDate) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "calendar.Event")
	proto.RegisterType((*EventList)(nil), "calendar.EventList")
	proto.RegisterType((*EventDeleteStatus)(nil), "calendar.EventDeleteStatus")
	proto.RegisterType((*EventDate)(nil), "calendar.EventDate")
}

func init() {
	proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c)
}

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xe5, 0x26, 0x0d, 0xf1, 0xf8, 0x00, 0x5d, 0x24, 0x64, 0x99, 0x03, 0x56, 0x2e, 0xe4,
	0x12, 0xaf, 0x14, 0xb8, 0xa0, 0x02, 0xe2, 0x4f, 0x81, 0x0b, 0x5c, 0x5c, 0x10, 0x12, 0x17, 0xb4,
	0xc9, 0x0e, 0xce, 0xaa, 0x8e, 0x77, 0xb5, 0x3b, 0x6e, 0xc5, 0xdb, 0xf1, 0x32, 0xbc, 0x07, 0xca,
	0xd8, 0x46, 0xc5, 0x12, 0x88, 0x9e, 0xec, 0xef, 0xdb, 0xf9, 0xcd, 0xce, 0x7c, 0x36, 0xc4, 0xca,
	0x99, 0xc2, 0x79, 0x4b, 0x56, 0xcc, 0xb7, 0xaa, 0xc6, 0x46, 0x2b, 0x9f, 0x3d, 0xa8, 0xac, 0xad,
	0x6a, 0x94, 0xec, 0x6f, 0xda, 0x6f, 0x92, 0xcc, 0x1e, 0x03, 0xa9, 0xbd, 0xeb, 0x4a, 0x17, 0x3f,
	0x22, 0x38, 0x7e, 0x73, 0x89, 0x0d, 0x09, 0x01, 0xd3, 0xb6, 0x35, 0x3a, 0x8d, 0xf2, 0x68, 0x19,
	0x97, 0xfc, 0x2e, 0x9e, 0x00, 0x04, 0x52, 0x9e, 0xbe, 0x1e, 0xb0, 0xf4, 0x28, 0x8f, 0x96, 0xc9,
	0x3a, 0x2b, 0xba, 0x9e, 0xc5, 0xd0, 0xb3, 0xf8, 0x38, 0xf4, 0x2c, 0x63, 0xae, 0x3e, 0x68, 0x91,
	0xc1, 0x5c, 0xb7, 0x5e, 0x91, 0xb1, 0x4d, 0x3a, 0xc9, 0xa3, 0xe5, 0xa4, 0xfc, 0xad, 0xc5, 0x3d,
	0x98, 0xed, 0x50, 0x69, 0xf4, 0xe9, 0x94, 0x2f, 0xeb, 0x95, 0xc8, 0x21, 0xd1, 0x18, 0xb6, 0xde,
	0x38, 0xc6, 0x8e, 0xf9, 0xf0, 0xba, 0xc5, 0x43, 0x06, 0xf4, 0xe9, 0xac, 0x1f, 0x32, 0xa0, 0x5f,
	0x3c, 0x86, 0x98, 0x37, 0x78, 0x6f, 0x02, 0x89, 0x87, 0x30, 0xc3, 0x83, 0x08, 0x69, 0x94, 0x4f,
	0x96, 0xc9, 0xfa, 0x76, 0x31, 0x64, 0x51, 0x70, 0x51, 0xd9, 0x1f, 0x2f, 0x56, 0x70, 0xc2, 0xc6,
	0x19, 0xd6, 0x48, 0x78, 0x4e, 0x8a, 0xda, 0x20, 0x52, 0xb8, 0xa5, 0x59, 0x77, 0x31, 0xcc, 0xcb,
	0x41, 0x2e, 0x4e, 0xfb, 0x4b, 0xce, 0x14, 0xa1, 0x28, 0x60, 0xaa, 0x15, 0x21, 0xd7, 0xfc, 0x3b,
	0x10, 0xae, 0x5b, 0xff, 0x3c, 0x82, 0xf8, 0xa5, 0x33, 0xe7, 0xe8, 0x2f, 0xd1, 0x0b, 0x09, 0xc9,
	0x6b, 0x8f, 0x8a, 0xb0, 0xcb, 0x7d, 0x3c, 0x61, 0x36, 0x36, 0x0e, 0xc0, 0x27, 0xa7, 0x6f, 0x00,
	0x9c, 0x42, 0xd2, 0xad, 0xf5, 0x17, 0xe0, 0xfe, 0xc8, 0xf8, 0x23, 0x83, 0xa7, 0x70, 0xe7, 0x1d,
	0x12, 0xfb, 0xe1, 0xad, 0xf5, 0xbc, 0xf0, 0xdd, 0x31, 0xa0, 0x08, 0xb3, 0xb1, 0xc9, 0xf9, 0x8f,
	0xe8, 0xcf, 0x88, 0x17, 0x37, 0xa0, 0x9f, 0xc1, 0xc9, 0x75, 0xfa, 0x83, 0x6d, 0x68, 0xf7, 0xff,
	0xf8, 0xab, 0x17, 0x5f, 0x9e, 0x57, 0x86, 0x76, 0xed, 0xa6, 0xd8, 0xda, 0xbd, 0x54, 0x8d, 0xfe,
	0x7e, 0x65, 0xaf, 0x64, 0x65, 0x6b, 0xd5, 0x54, 0xab, 0x1a, 0x43, 0xb0, 0x4d, 0x90, 0xdd, 0x73,
	0x35, 0xe0, 0xd2, 0x5d, 0x54, 0x92, 0xff, 0x09, 0xe5, 0xcc, 0x66, 0xc6, 0xdf, 0xf0, 0xd1, 0xaf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x49, 0xd2, 0x3a, 0x37, 0x4d, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ApiServerClient is the client API for ApiServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApiServerClient interface {
	// CreateEvent create event
	CreateEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Event, error)
	// UpdateEvent update event
	UpdateEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Event, error)
	// DeteleEvent delete event
	DeleteEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*EventDeleteStatus, error)
	// GetEventsForDate get events for date
	GetEventsForDate(ctx context.Context, in *EventDate, opts ...grpc.CallOption) (*EventList, error)
	// GetEventsForWeek get events for weak
	GetEventsForWeek(ctx context.Context, in *EventDate, opts ...grpc.CallOption) (*EventList, error)
	// GetEventsForMonth get events for month
	GetEventsForMonth(ctx context.Context, in *EventDate, opts ...grpc.CallOption) (*EventList, error)
}

type apiServerClient struct {
	cc grpc.ClientConnInterface
}

func NewApiServerClient(cc grpc.ClientConnInterface) ApiServerClient {
	return &apiServerClient{cc}
}

func (c *apiServerClient) CreateEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Event, error) {
	out := new(Event)
	err := c.cc.Invoke(ctx, "/calendar.ApiServer/CreateEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServerClient) UpdateEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Event, error) {
	out := new(Event)
	err := c.cc.Invoke(ctx, "/calendar.ApiServer/UpdateEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServerClient) DeleteEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*EventDeleteStatus, error) {
	out := new(EventDeleteStatus)
	err := c.cc.Invoke(ctx, "/calendar.ApiServer/DeleteEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServerClient) GetEventsForDate(ctx context.Context, in *EventDate, opts ...grpc.CallOption) (*EventList, error) {
	out := new(EventList)
	err := c.cc.Invoke(ctx, "/calendar.ApiServer/GetEventsForDate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServerClient) GetEventsForWeek(ctx context.Context, in *EventDate, opts ...grpc.CallOption) (*EventList, error) {
	out := new(EventList)
	err := c.cc.Invoke(ctx, "/calendar.ApiServer/GetEventsForWeek", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServerClient) GetEventsForMonth(ctx context.Context, in *EventDate, opts ...grpc.CallOption) (*EventList, error) {
	out := new(EventList)
	err := c.cc.Invoke(ctx, "/calendar.ApiServer/GetEventsForMonth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServerServer is the server API for ApiServer service.
type ApiServerServer interface {
	// CreateEvent create event
	CreateEvent(context.Context, *Event) (*Event, error)
	// UpdateEvent update event
	UpdateEvent(context.Context, *Event) (*Event, error)
	// DeteleEvent delete event
	DeleteEvent(context.Context, *Event) (*EventDeleteStatus, error)
	// GetEventsForDate get events for date
	GetEventsForDate(context.Context, *EventDate) (*EventList, error)
	// GetEventsForWeek get events for weak
	GetEventsForWeek(context.Context, *EventDate) (*EventList, error)
	// GetEventsForMonth get events for month
	GetEventsForMonth(context.Context, *EventDate) (*EventList, error)
}

// UnimplementedApiServerServer can be embedded to have forward compatible implementations.
type UnimplementedApiServerServer struct {
}

func (*UnimplementedApiServerServer) CreateEvent(ctx context.Context, req *Event) (*Event, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEvent not implemented")
}
func (*UnimplementedApiServerServer) UpdateEvent(ctx context.Context, req *Event) (*Event, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEvent not implemented")
}
func (*UnimplementedApiServerServer) DeleteEvent(ctx context.Context, req *Event) (*EventDeleteStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEvent not implemented")
}
func (*UnimplementedApiServerServer) GetEventsForDate(ctx context.Context, req *EventDate) (*EventList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEventsForDate not implemented")
}
func (*UnimplementedApiServerServer) GetEventsForWeek(ctx context.Context, req *EventDate) (*EventList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEventsForWeek not implemented")
}
func (*UnimplementedApiServerServer) GetEventsForMonth(ctx context.Context, req *EventDate) (*EventList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEventsForMonth not implemented")
}

func RegisterApiServerServer(s *grpc.Server, srv ApiServerServer) {
	s.RegisterService(&_ApiServer_serviceDesc, srv)
}

func _ApiServer_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServerServer).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.ApiServer/CreateEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServerServer).CreateEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiServer_UpdateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServerServer).UpdateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.ApiServer/UpdateEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServerServer).UpdateEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiServer_DeleteEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServerServer).DeleteEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.ApiServer/DeleteEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServerServer).DeleteEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiServer_GetEventsForDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventDate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServerServer).GetEventsForDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.ApiServer/GetEventsForDate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServerServer).GetEventsForDate(ctx, req.(*EventDate))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiServer_GetEventsForWeek_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventDate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServerServer).GetEventsForWeek(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.ApiServer/GetEventsForWeek",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServerServer).GetEventsForWeek(ctx, req.(*EventDate))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiServer_GetEventsForMonth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventDate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServerServer).GetEventsForMonth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.ApiServer/GetEventsForMonth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServerServer).GetEventsForMonth(ctx, req.(*EventDate))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApiServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calendar.ApiServer",
	HandlerType: (*ApiServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEvent",
			Handler:    _ApiServer_CreateEvent_Handler,
		},
		{
			MethodName: "UpdateEvent",
			Handler:    _ApiServer_UpdateEvent_Handler,
		},
		{
			MethodName: "DeleteEvent",
			Handler:    _ApiServer_DeleteEvent_Handler,
		},
		{
			MethodName: "GetEventsForDate",
			Handler:    _ApiServer_GetEventsForDate_Handler,
		},
		{
			MethodName: "GetEventsForWeek",
			Handler:    _ApiServer_GetEventsForWeek_Handler,
		},
		{
			MethodName: "GetEventsForMonth",
			Handler:    _ApiServer_GetEventsForMonth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
